name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - main
      - develop
    types:
      - completed

jobs:
  staging:
    runs-on: ubuntu-latest
    environment: staging
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run deploy script
        run: echo '[TODO] Add customer script to deploy to staging'

  production:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run deploy script
        run: echo '[TODO] Add customer script to deploy to production'
